### ISSUE TITLE
KeyValidator doesn't support text/code meta data in messages

### ISSUE THREAD

**Issue by fgi** [dry-rb/dry-schema#310]
Hello,

**Describe the bug**

I need error messages with codes and texts. So I use the 'meta' feature in my messages files (hashes with `text` and `code` keys).
I activate the KeyValidator option:  `config.validate_keys = true`.
I have 2 formatting issues:
* The produced error does not have a structure as hash with the `code`  and  `text` keys.
* The produced error does not seem to use the `full: true` option to add the key into the error text.

**To Reproduce**

````
# my_messages.yml

en:
  dry_validation_with_codes:
    or: "or"

    errors:
      unexpected_key:
        text: "is not allowed"
        code: "is_not_allowed"
      key?:
        text: "is missing"
        code: "missing"
````

````
# my_contract.rb

require 'dry/validation/contract'

class MyContract < Dry::Validation::Contract
  # Define a top namespace and use only my messages file in loaded paths
  # to avoid conflict with default messages from the gem.
  config.messages.top_namespace = 'dry_validation_with_codes'
  config.messages.load_paths = ['my_messages.yml']
  config.validate_keys = true

  params do
    required(:title).filled
  end
end


result = MyContract.new.call({})
puts result.errors(full: true).to_h.inspect
# => {:title=>[{:text=>"title is missing", :code=>"missing"}]}
# OK

result = MyContract.new.call({badkey: "value"})
puts result.errors(full: true).to_h.inspect

# => {:badkey=>["is not allowed"], :title=>[{:text=>"title is missing", :code=>"missing"}]}
# Not OK, expected result:
# {:badkey=>[{:text=>"badkey is not allowed" :code=>"is_not_allowed"}]}, :title=>[{:text=>"title is missing", :code=>"missing"}]}
````

**Expected behavior**

Expected result for KeyValidator message: 
`{:badkey=>[{:text=>"badkey is not allowed", :code=>"is_not_allowed"}]}`

Observed result: 
`{:badkey=>["is not allowed"]}`

**Your environment**

- Affects my production application: **NO**
- Ruby version: ruby 2.7.1p83
- Gem dry-validation: 1.5.4
- OS: FreeBSD 12.1

Thank you.
