### ISSUE TITLE
Same locale namespace for nested schemas with different configuration

### ISSUE THREAD

**Issue by iliabylich** [dry-rb/dry-schema#49]
Let's say I have two schemas:
``` ruby
CommentSchema = Dry::Validation.Schema(ApplicationSchema) do
  configure do
    config.namespace = :comment
  end

  required(:comment_body).filled
end

PostSchema = Dry::Validation.Schema(ApplicationSchema) do
  configure do
    config.namespace = :post
  end

  required(:post_body).filled
  required(:comment).schema(CommentSchema)
end
```

And I have the following lines in my `en.yml`:
```
en:
  errors:
    rules:
      comment:
        rules:
          comment_body:
            filled?: "COMMENT can't be blank"

      post:
        rules:
          post_body:
            filled?: "POST can't be blank"
```

When I call them independently error messages are correct:
``` ruby
PostSchema.call(post_body: '').errors
# =>  {:post_body=>["POST can't be blank"], :comment=>["is missing"]}
CommentSchema.call(comment_body: '').errors
# => {:comment_body=>["COMMENT can't be blank"]}
```

But when I put comment parameters inside post parameters dry-validation uses only default errors for nested parameters:
``` ruby
PostSchema.call(post_body: '', comment: { comment_body: '' })
{:post_body=>["POST can't be blank"], :comment=>{:comment_body=>["must be filled"]}}
```

On my project we have a very noisy i18n backend, here's the list of the keys that dry-validation checks - https://gist.github.com/iliabylich/6c0db70a547fb4ba5d14c6f3d1d5ac36. As you may see it tries to get keys like `errors.rules.post.comment_body.failure` (which means that it ignores configured `config.namespace` for nested schema)

First of all, is it a bug or misconfiguration? Does dry-validation support it?
