### ISSUE TITLE
Deeply nested namespaced messages

### ISSUE THREAD

**Issue by badlamer** [dry-rb/dry-schema#50]
``` yml
en:
  errors:
    rules:
      email:
        filled?: "the email is missing"

      user:
        filled?: "name cannot be blank"

        rules:
          address:
            filled?: "You gotta tell us where you live"
```

Please example for more nested rule message.
